### ISSUE TITLE
Compilation

### ISSUE THREAD

**Issue by BizCub** [EvanHsieh0415/WoolTweaks-Datapack#2]
Not a issue, but can you tell me how to make a mod from a datapack. I know that I need to somehow use some code from git modrinth, but I don't know how. Thank you in advance

**Comment by EvanHsieh0415** [comment]
> Not a issue, but can you tell me how to make a mod from a datapack. I know that I need to somehow use some code from git modrinth, but I don't know how. Thank you in advance

On the modrinth version page you can press the `Package as mod` button to package the data pack as a mod.

![image](https://github.com/Mango-Minecraft-Project/WoolRecipes-DataPack/assets/74277414/11e57521-9f1b-4010-8b96-d648db48b349)

**Comment by BizCub** [comment]
Thanks for the answer
